-- MySQL Script generated by MySQL Workbench
-- Tue Mar 31 18:06:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoPI
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetoPI` ;

DROP TABLE IF EXISTS `projetoPI`.`endereco` ;
DROP TABLE IF EXISTS `projetoPI`.`avaliacao` ;
DROP TABLE IF EXISTS `projetoPI`.`compra` ;
DROP TABLE IF EXISTS `projetoPI`.`genero` ;
DROP TABLE IF EXISTS `projetoPI`.`livro` ;
DROP TABLE IF EXISTS `projetoPI`.`usuario` ;
DROP TABLE IF EXISTS `projetoPI`.`venda` ;


-- -----------------------------------------------------
-- Schema projetoPI
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoPI` DEFAULT CHARACTER SET utf8 ;
USE `projetoPI` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetoPI`.`endereco` (
  `id_endereco` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(60) NOT NULL,
  `num` INT NOT NULL,
  `cep` INT NOT NULL,
  `comp` VARCHAR(100) NULL,
  PRIMARY KEY (`id_endereco`),
  UNIQUE INDEX `idEndereco_UNIQUE` (`id_endereco` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`avaliacao`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetoPI`.`avaliacao` (
  `id_avaliacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nota` INT NOT NULL,
  `comentario` VARCHAR(1000) NULL,
  `avaliado` INT NOT NULL,
  `avaliador` INT NOT NULL,
  PRIMARY KEY (`id_avaliacao`),
  UNIQUE INDEX `id_avaliacao_UNIQUE` (`id_avaliacao` ASC),
  INDEX `fk_avaliacao_usuario1_idx` (`avaliado` ASC),
  INDEX `fk_avaliacao_usuario2_idx` (`avaliador` ASC),
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`avaliado`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_usuario2`
    FOREIGN KEY (`avaliador`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`compra`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetoPI`.`compra` (
  `id_venda` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `valor` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `metodo_pgto` VARCHAR(45) NOT NULL,
  `qtd` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `compra` VARCHAR(45) NULL,
  `livro_id_livro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venda`),
  UNIQUE INDEX `id_venda_UNIQUE` (`id_venda` ASC),
  INDEX `fk_compra_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_compra_livro1_idx` (`livro_id_livro` ASC),
  CONSTRAINT `fk_compra_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_livro1`
    FOREIGN KEY (`livro_id_livro`)
    REFERENCES `projetoPI`.`livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`genero`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetoPI`.`genero` (
  `id_genero` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genero`),
  UNIQUE INDEX `id_genero_UNIQUE` (`id_genero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`livro`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetoPI`.`livro` (
  `id_livro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `isbn` INT NOT NULL,
  `titulo` VARCHAR(40) NOT NULL,
  `autor` VARCHAR(40) NOT NULL,
  `editora` VARCHAR(30) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `descricao` VARCHAR(500),
  `estado` VARCHAR(30),
  `genero_id_genero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_livro`),
  UNIQUE INDEX `id_livro_UNIQUE` (`id_livro` ASC),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC),
  INDEX `fk_livro_genero_idx` (`genero_id_genero` ASC),
  CONSTRAINT `fk_livro_genero`
    FOREIGN KEY (`genero_id_genero`)
    REFERENCES `projetoPI`.`genero` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`usuario`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetoPI`.`usuario` (
  `id_usuario` INT NOT NULL auto_increment,
  `nome_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  `cpf` INT NULL,
  `fone` INT NULL,
  `Endereco_id_endereco` INT UNSIGNED ,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `fone_UNIQUE` (`fone` ASC),
  INDEX `fk_usuario_Endereco1_idx` (`Endereco_id_endereco` ASC),
  CONSTRAINT `fk_usuario_Endereco1`
    FOREIGN KEY (`Endereco_id_endereco`)
    REFERENCES `projetoPI`.`Endereco` (`id_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoPI`.`venda`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetoPI`.`venda` (
  `id_venda` INT NOT NULL,
  `qtd` INT NOT NULL,
  `venda_id_venda` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `livro_id_livro` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_usuario1_idx` (`usuario_id_usuario` ASC),
  INDEX `fk_venda_livro1_idx` (`livro_id_livro` ASC),
  CONSTRAINT `fk_venda_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `projetoPI`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_livro1`
    FOREIGN KEY (`livro_id_livro`)
    REFERENCES `projetoPI`.`livro` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into genero(tipo) 
values('romance'),
('ação'),
('YA'),
('nao ficçao'),
('indefinido');


SELECT * FROM  `projetoPI`.`Endereco` ;
SELECT * FROM  `projetoPI`.`avaliacao` ;
SELECT * FROM  `projetoPI`.`compra` ;
SELECT * FROM  `projetoPI`.`genero` ;
SELECT * FROM  `projetoPI`.`livro` ;
SELECT * FROM  `projetoPI`.`usuario` ;
SELECT * FROM  `projetoPI`.`venda` ;

SELECT id_livro, isbn, titulo, autor, editora, preco, genero_id_genero, id_genero, tipo FROM  projetoPI.livro l inner join projetoPI.genero g on l.id_livro=g.id_genero ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
